version: 2

jobs:
  build:
    docker:
      - image: alexwijn/docker-git-php-composer
    working_directory: ~/repo
    branches:
      only:
        - master
        - dev
    steps:
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              ssh -o "StrictHostKeyChecking no" ${USER}@${DEV_DOMAIN} '
              cd /home/pbc_cg/dev.cg.providencedenver.org &&
              git pull origin dev &&
              composer install &&
              cd web &&
              drush --root=/home/pbc_cg/dev.cg.providencedenver.org/web cim -y'
            fi
