version: 2

jobs:
  build:
    docker:
      - image: alexwijn/docker-git-php-composer
    working_directory: ~/repo
    branches:
      only:
        - dev
    steps:
      - run: ssh -o "StrictHostKeyChecking no" ${USER}@dev.cg.providencedenver.org 'cd /home/pbc_cg/dev.cg.providencedenver.org && touch circleworksnow.txt'
