version: 2

jobs:
  build:
    docker:
      - image: alexwijn/docker-git-php-composer
    working_directory: ~/repo
    branches:
      only:
        - dev
    steps:
      - run: ssh -o "StrictHostKeyChecking no" $USER@dev.cg.providencedenver.org 'cd $DEV_ROOT && touch circleworksnow.txt'
