version: 2

jobs:
  build:
  deploy:
    machine:
      enabled: true
    branches:
      only:
        - master
        - dev
    steps:
      - run:
          name: Deploy to Dreamhost
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              ssh -o "StrictHostKeyChecking no" ${USER}@${DEV_DOMAIN} '
              cd /home/pbc_cg/dev.cg.providencedenver.org &&
              git pull origin dev &&
              composer install --no-dev &&
              cd web &&
              drush --root=/home/pbc_cg/dev.cg.providencedenver.org/web cim -y && drush --root=/home/pbc_cg/dev.cg.providencedenver.org/web updb -y
              '
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o "StrictHostKeyChecking no" ${USER}@${DEV_DOMAIN} '
              cd /home/pbc_cg/cg.providencedenver.org &&
              git pull origin master &&
              composer install --no-dev &&
              cd web &&
              drush --root=/home/pbc_cg/cg.providencedenver.org/web cim -y && drush --root=/home/pbc_cg/cg.providencedenver.org/web updb -y
              '
            fi
