version: 2

jobs:
  build:
    docker:
      - image: circleci/php:latest
    working_directory: ~/repo
    branches:
      only:
        - master
        - dev
    steps:
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              ssh -o "StrictHostKeyChecking no" ${USER}@${DEV_DOMAIN} '
              cd /home/pbc_cg/dev.cg.providencedenver.org &&
              git pull origin dev &&
              composer install --no-dev &&
              cd web &&
              drush updb -y && drush cim -y
              '
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o "StrictHostKeyChecking no" ${USER}@${DEV_DOMAIN} '
              cd /home/pbc_cg/cg.providencedenver.org &&
              git pull origin master &&
              composer install --no-dev &&
              cd web &&
              drush updb -y && drush cim -y
              '
            fi
