version: 2

jobs:
  build:
    docker:
      - image: alexwijn/docker-git-php-composer
    working_directory: ~/repo
    steps:
      - checkout
      - run: ssh -o "StrictHostKeyChecking no" pbc_cg@dev.cg.providencedenver.org && touch circleworks.txt
