name: Deploy CG App

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          command: |
            cd ~/cg.providencedenver.org/
            git pull
            composer install --no-dev --optimize-autoloader --prefer-dist --no-interaction
            cd ~/cg.providencedenver.org/web/
            drush sql-dump --extra-dump=--no-tablespaces > ~/backups/cg_prod_`date +%Y-%m-%d-%H.%M.%S`.sql
            drush deploy
