name: Process Queue

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  process-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Process Queue
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/cg.providencedenver.org/web
            ../vendor/drush/drush/drush queue-run pco_webhooks_processor
